# Generated by Django 2.2.3 on 2021-05-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20210430_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacanciess',
            name='choosemo',
            field=models.CharField(choices=[('до налогов', 'до налогов'), ('в руках', 'в руках')], max_length=100),
        ),
        migrations.AlterField(
            model_name='vacanciess',
            name='emptype',
            field=models.CharField(choices=[('Полная занятость', 'Полная занятость'), ('Неполная занятость', 'Неполная занятость'), ('Проектная работа или разовое задание', 'Проектная работа или разовое задание'), ('Волонтерство', 'Волонтерство'), ('Практика', 'Практика')], max_length=100),
        ),
    ]
