# Generated by Django 2.2.3 on 2021-05-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20210502_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacanciess',
            name='worhou',
            field=models.CharField(choices=[('Полный день', 'Полный день'), ('Сменная работа', 'Сменная работа'), ('По таблицах', 'По таблицах'), ('Долгая работа', 'Долгая работа')], max_length=100),
        ),
    ]
