# Generated by Django 2.2.3 on 2021-04-27 10:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_auto_20210426_2127'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('summary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='name',
        ),
        migrations.AddField(
            model_name='summary',
            name='data_time',
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summary',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Ism'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summary',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Familya'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summary',
            name='phone_name',
            field=models.CharField(max_length=100, verbose_name='Telefon nomer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summary',
            name='provinces',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.Uzbekiston_provinces'),
        ),
        migrations.AddField(
            model_name='summary',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.Uzbekiston_region'),
        ),
        migrations.AddField(
            model_name='summary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
