# Generated by Django 2.2.3 on 2021-04-27 14:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_auto_20210426_2127'),
        ('summary', '0002_auto_20210427_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='citizenship',
            field=models.ManyToManyField(to='category.Citizenship'),
        ),
        migrations.AddField(
            model_name='summary',
            name='sex',
            field=models.CharField(choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], default=datetime.datetime(2021, 4, 27, 14, 45, 15, 641626, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
