# Generated by Django 2.2.3 on 2021-04-27 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0003_auto_20210427_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workexperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begwork', models.DateField()),
                ('finishw', models.DateField()),
                ('organiza', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('workplaceres', models.TextField(verbose_name='Ish joyingizdagi vazifa haqida yozing')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Workexperience', to='summary.Summary')),
            ],
            options={
                'db_table': 'Workexperience',
            },
        ),
    ]
