# Generated by Django 2.2.3 on 2021-04-27 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0006_auto_20210427_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=32)),
                ('english', models.CharField(max_length=3)),
                ('nepali', models.CharField(max_length=3)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='summary.Summary')),
            ],
            options={
                'db_table': 'marks',
            },
        ),
        migrations.DeleteModel(
            name='Workexperience',
        ),
    ]
