# Generated by Django 2.2.3 on 2021-04-27 20:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0008_auto_20210427_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='workexper',
            field=models.CharField(choices=[('Ish tajribasi bor', 'Ish tajribasi bor'), ("Ish tajribasi yo'q", "Ish tajribasi yo'q")], default=datetime.datetime(2021, 4, 27, 20, 12, 13, 430619, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
