# Generated by Django 2.2.3 on 2021-04-28 04:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0010_auto_20210428_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='begwork',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 4, 28, 4, 53, 58, 20280, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='finishw',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 4, 28, 4, 54, 0, 700604, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
