# Generated by Django 2.2.3 on 2021-04-28 08:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0012_auto_20210428_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='moneys',
            field=models.CharField(choices=[('USD', 'USD'), ('RUB', 'RUB'), ('UZS', 'UZS')], default=datetime.datetime(2021, 4, 28, 8, 58, 57, 517785, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summary',
            name='thesalary',
            field=models.CharField(default=datetime.datetime(2021, 4, 28, 8, 59, 6, 398367, tzinfo=utc), max_length=100, verbose_name='$$$'),
            preserve_default=False,
        ),
    ]
