# Generated by Django 2.2.3 on 2021-04-28 13:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0014_auto_20210428_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 4, 28, 13, 26, 59, 567221, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
