# Generated by Django 2.2.3 on 2021-04-30 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0015_summary_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summary',
            options={'verbose_name': "E'LON TARJIMAI HOL", 'verbose_name_plural': "E'LON TARJIMAI HOL"},
        ),
    ]
