# Generated by Django 2.2.3 on 2021-05-01 06:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0016_auto_20210430_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='carobjec',
            field=models.CharField(default=datetime.datetime(2021, 5, 1, 6, 35, 54, 821843, tzinfo=utc), max_length=100, verbose_name='Kareriya maqsadi'),
            preserve_default=False,
        ),
    ]
