# Generated by Django 2.2.3 on 2021-05-01 08:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0017_summary_carobjec'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='key_skills',
            field=models.TextField(default=datetime.datetime(2021, 5, 1, 8, 51, 42, 236632, tzinfo=utc), verbose_name='Talluqli ishlar'),
            preserve_default=False,
        ),
    ]
