# Generated by Django 2.2.3 on 2021-05-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0018_summary_key_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='key_skills',
            field=models.TextField(verbose_name='Talluqli soxalar'),
        ),
    ]
