# Generated by Django 2.2.3 on 2021-05-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0020_auto_20210501_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='workexper',
            field=models.CharField(choices=[('Есть опыт работы', 'Есть опыт работы'), ('Нет опыта работы', 'Нет опыта работы')], max_length=100),
        ),
    ]
