# Generated by Django 2.2.3 on 2021-05-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0021_auto_20210502_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='sex',
            field=models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=100),
        ),
    ]
