# Generated by Django 2.2.3 on 2021-04-26 07:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=datetime.datetime(2021, 4, 26, 7, 29, 34, 772678, tzinfo=utc), max_length=150, unique=True, verbose_name='username'),
            preserve_default=False,
        ),
    ]
