# Generated by Django 2.2.3 on 2021-04-27 05:43

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_vacancies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '1. All users Database', 'verbose_name_plural': '1. All users Database'},
        ),
        migrations.AlterModelOptions(
            name='vacancies',
            options={'verbose_name': '1. Useradminpage', 'verbose_name_plural': '1. Useradminpage'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='vacancies',
            old_name='vacancies_image',
            new_name='vacan_image',
        ),
        migrations.RemoveField(
            model_name='vacancies',
            name='provinces',
        ),
        migrations.RemoveField(
            model_name='vacancies',
            name='region',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=datetime.datetime(2021, 4, 27, 5, 43, 32, 828852, tzinfo=utc), error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
