# Generated by Django 2.2.3 on 2021-04-27 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_auto_20210426_2127'),
        ('accounts', '0008_auto_20210427_0843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancies',
            options={'verbose_name': '2. Vacancies', 'verbose_name_plural': '2. Vacancies'},
        ),
        migrations.AddField(
            model_name='vacancies',
            name='provinces',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.Uzbekiston_provinces'),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.Uzbekiston_region'),
        ),
    ]
