# Generated by Django 2.2.3 on 2021-04-29 07:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210427_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancies',
            name='choose',
            field=models.CharField(choices=[('yuridik shaxs', 'yuridik shaxs'), ('xususiy', 'xususiy'), ('boshqalar', 'boshqalar')], default=datetime.datetime(2021, 4, 29, 7, 6, 25, 733884, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
