# Generated by Django 2.2.3 on 2021-04-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_vacancies_choose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='choose',
            field=models.CharField(choices=[('yuridik shaxs', 'yuridik shaxs'), ('jismonoy shaxs', 'jismonoy shaxs'), ('boshqalar', 'boshqalar')], max_length=100),
        ),
    ]
