# Generated by Django 2.2.3 on 2021-05-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210430_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='choose',
            field=models.CharField(choices=[('юридического лица', 'юридического лица'), ('физическое лицо', 'физическое лицо'), ('другие', 'другие')], max_length=100),
        ),
    ]
