# Generated by Django 2.2.3 on 2021-04-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Andijon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': '0003. Andijon viloyati',
                'verbose_name_plural': '0003. Andijon viloyati',
            },
        ),
        migrations.CreateModel(
            name='Buxoro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': '0012. Buxoro viloyati',
                'verbose_name_plural': '0012. Buxoro viloyati',
            },
        ),
        migrations.CreateModel(
            name='Citizenship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': '0001. Fuqarolik',
                'verbose_name_plural': '0001. Fuqarolik',
            },
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': '00002. Bandlik',
                'verbose_name_plural': '00002. Bandlik',
            },
        ),
        migrations.CreateModel(
            name='Fargona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': '0004. Fargʻona viloyati',
                'verbose_name_plural': '0004. Fargʻona viloyati',
            },
        ),
        migrations.CreateModel(
            name='Jizzax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': '0006. Jizzax viloyati',
                'verbose_name_plural': '0006. Jizzax viloyati',
            },
        ),
        migrations.CreateModel(
            name='Namangan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': '0005. Namangan viloyati',
                'verbose_name_plural': '0005. Namangan viloyati',
            },
        ),
        migrations.CreateModel(
            name='Navoiy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': '0011. Navoiy viloyati',
                'verbose_name_plural': '0011. Navoiy viloyati',
            },
        ),
        migrations.CreateModel(
            name='Qashqadaryo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': '0010. Qashqadaryo viloyati',
                'verbose_name_plural': '0010. Qashqadaryo viloyati',
            },
        ),
        migrations.CreateModel(
            name='Qoraqalpogiston',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': '0014. Qoraqalpogʻiston Respublikasi',
                'verbose_name_plural': '0014. Qoraqalpogʻiston Respublikasi',
            },
        ),
        migrations.CreateModel(
            name='Relocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': "00001. Boshqa joyga ko'chirish",
                'verbose_name_plural': "00001. Boshqa joyga ko'chirish",
            },
        ),
        migrations.CreateModel(
            name='Samarqand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': '0007. Samarqand viloyati',
                'verbose_name_plural': '0007. Samarqand viloyati',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': '00003. Ish grafigi',
                'verbose_name_plural': '00003. Ish grafigi',
            },
        ),
        migrations.CreateModel(
            name='Sirdaryo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': '0008. Sirdaryo viloyati',
                'verbose_name_plural': '0008. Sirdaryo viloyati',
            },
        ),
        migrations.CreateModel(
            name='Surxondaryo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': '0009. Surxondaryo viloyati',
                'verbose_name_plural': '0009. Surxondaryo viloyati',
            },
        ),
        migrations.CreateModel(
            name='Toshkent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': '0002. Toshkent viloyati',
                'verbose_name_plural': '0002. Toshkent viloyati',
            },
        ),
        migrations.CreateModel(
            name='Work1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': '01. Avtomobil biznesi',
                'verbose_name_plural': '01. Avtomobil biznesi',
            },
        ),
        migrations.CreateModel(
            name='Work10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': '10. Xarid qilish',
                'verbose_name_plural': '10. Xarid qilish',
            },
        ),
        migrations.CreateModel(
            name='Work11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': "11. O'rnatish va xizmat ko'rsatish",
                'verbose_name_plural': "11. O'rnatish va xizmat ko'rsatish",
            },
        ),
        migrations.CreateModel(
            name='Work12',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': '12. Axborot texnologiyalari, internet, telekom',
                'verbose_name_plural': '12. Axborot texnologiyalari, internet, telekom',
            },
        ),
        migrations.CreateModel(
            name='Work13',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': "13. San'at, ko'ngil ochish, ommaviy axborot vositalari",
                'verbose_name_plural': "13. San'at, ko'ngil ochish, ommaviy axborot vositalari",
            },
        ),
        migrations.CreateModel(
            name='Work14',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': '14. Psixologik konsultatsiya',
                'verbose_name_plural': '14. Psixologik konsultatsiya',
            },
        ),
        migrations.CreateModel(
            name='Work15',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': '15. Marketing, reklama',
                'verbose_name_plural': '15. Marketing, reklama',
            },
        ),
        migrations.CreateModel(
            name='Work16',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': '16. Tibbiyot, farmatsevtika',
                'verbose_name_plural': '16. Tibbiyot, farmatsevtika',
            },
        ),
        migrations.CreateModel(
            name='Work17',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': "17. Ilm-fan, ta'lim",
                'verbose_name_plural': "17. Ilm-fan, ta'lim",
            },
        ),
        migrations.CreateModel(
            name='Work18',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': '18. Ishga qabul qilish, talabalar',
                'verbose_name_plural': '18. Ishga qabul qilish, talabalar',
            },
        ),
        migrations.CreateModel(
            name='Work19',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': '19. Sotish',
                'verbose_name_plural': '19. Sotish',
            },
        ),
        migrations.CreateModel(
            name='Work2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': "02. Ma'muriy xodimlar",
                'verbose_name_plural': "02. Ma'muriy xodimlar",
            },
        ),
        migrations.CreateModel(
            name='Work20',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': "20. Ishlab chiqarish, qishloq xo'jaligi",
                'verbose_name_plural': "20. Ishlab chiqarish, qishloq xo'jaligi",
            },
        ),
        migrations.CreateModel(
            name='Work21',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': '21. Ishchi xodimlar',
                'verbose_name_plural': '21. Ishchi xodimlar',
            },
        ),
        migrations.CreateModel(
            name='Work22',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': "22. Sport klublari, fitness, go'zallik salonlari",
                'verbose_name_plural': "22. Sport klublari, fitness, go'zallik salonlari",
            },
        ),
        migrations.CreateModel(
            name='Work23',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': "23. Sug'urta",
                'verbose_name_plural': "23. Sug'urta",
            },
        ),
        migrations.CreateModel(
            name='Work24',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': "24. Qurilish, ko'chmas mulk",
                'verbose_name_plural': "24. Qurilish, ko'chmas mulk",
            },
        ),
        migrations.CreateModel(
            name='Work25',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': '25. Transport, logistika',
                'verbose_name_plural': '25. Transport, logistika',
            },
        ),
        migrations.CreateModel(
            name='Work26',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': '26. Turizm, mehmonxonalar, restoranlar',
                'verbose_name_plural': '26. Turizm, mehmonxonalar, restoranlar',
            },
        ),
        migrations.CreateModel(
            name='Work27',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': '27. Xodimlarni boshqarish, treninglar',
                'verbose_name_plural': '27. Xodimlarni boshqarish, treninglar',
            },
        ),
        migrations.CreateModel(
            name='Work28',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': '28. Advokatlar',
                'verbose_name_plural': '28. Advokatlar',
            },
        ),
        migrations.CreateModel(
            name='Work3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': '03. Banklar, investitsiyalar, lizing',
                'verbose_name_plural': '03. Banklar, investitsiyalar, lizing',
            },
        ),
        migrations.CreateModel(
            name='Work4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': '04. Xavfsizlik',
                'verbose_name_plural': '04. Xavfsizlik',
            },
        ),
        migrations.CreateModel(
            name='Work5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': '05. Buxgal teriya hisobi, boshqaruv hisobi, korxona moliyasi',
                'verbose_name_plural': '05. Buxgal teriya hisobi, boshqaruv hisobi, korxona moliyasi',
            },
        ),
        migrations.CreateModel(
            name='Work6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': '06. Yuqori menejment',
                'verbose_name_plural': '06. Yuqori menejment',
            },
        ),
        migrations.CreateModel(
            name='Work7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': '07. Davlat xizmati, notijorat tashkilotlari',
                'verbose_name_plural': '07. Davlat xizmati, notijorat tashkilotlari',
            },
        ),
        migrations.CreateModel(
            name='Work8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': '08. Xom ashyolarni qazib olish',
                'verbose_name_plural': '08. Xom ashyolarni qazib olish',
            },
        ),
        migrations.CreateModel(
            name='Work9',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': '09. Mahalliy xodimlar',
                'verbose_name_plural': '09. Mahalliy xodimlar',
            },
        ),
        migrations.CreateModel(
            name='Xorazm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': '0013. Xorazm viloyati',
                'verbose_name_plural': '0013. Xorazm viloyati',
            },
        ),
    ]
