# Generated by Django 2.2.3 on 2021-04-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uzbekiston_provinces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinces', models.CharField(max_length=100, verbose_name='Nomi')),
                ('region', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': '0002. Uzbekiston viloyatlari',
                'verbose_name_plural': '0002. Uzbekiston viloyatlari',
            },
        ),
        migrations.DeleteModel(
            name='Andijon',
        ),
        migrations.DeleteModel(
            name='Buxoro',
        ),
        migrations.DeleteModel(
            name='Fargona',
        ),
        migrations.DeleteModel(
            name='Jizzax',
        ),
        migrations.DeleteModel(
            name='Namangan',
        ),
        migrations.DeleteModel(
            name='Navoiy',
        ),
        migrations.DeleteModel(
            name='Qashqadaryo',
        ),
        migrations.DeleteModel(
            name='Qoraqalpogiston',
        ),
        migrations.DeleteModel(
            name='Samarqand',
        ),
        migrations.DeleteModel(
            name='Sirdaryo',
        ),
        migrations.DeleteModel(
            name='Surxondaryo',
        ),
        migrations.DeleteModel(
            name='Toshkent',
        ),
        migrations.DeleteModel(
            name='Xorazm',
        ),
    ]
