# Generated by Django 2.2.3 on 2021-04-26 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20210426_2055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uzbekiston_region',
            options={'verbose_name': '0003. Uzbekiston tumanlari', 'verbose_name_plural': '0003. Uzbekiston tumanlari'},
        ),
    ]
