# Generated by Django 2.2.3 on 2021-04-28 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_auto_20210426_2127'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Work5',
            new_name='Specialization',
        ),
        migrations.DeleteModel(
            name='Work1',
        ),
        migrations.DeleteModel(
            name='Work10',
        ),
        migrations.DeleteModel(
            name='Work11',
        ),
        migrations.DeleteModel(
            name='Work12',
        ),
        migrations.DeleteModel(
            name='Work13',
        ),
        migrations.DeleteModel(
            name='Work14',
        ),
        migrations.DeleteModel(
            name='Work15',
        ),
        migrations.DeleteModel(
            name='Work16',
        ),
        migrations.DeleteModel(
            name='Work17',
        ),
        migrations.DeleteModel(
            name='Work18',
        ),
        migrations.DeleteModel(
            name='Work19',
        ),
        migrations.DeleteModel(
            name='Work2',
        ),
        migrations.DeleteModel(
            name='Work20',
        ),
        migrations.DeleteModel(
            name='Work21',
        ),
        migrations.DeleteModel(
            name='Work22',
        ),
        migrations.DeleteModel(
            name='Work23',
        ),
        migrations.DeleteModel(
            name='Work24',
        ),
        migrations.DeleteModel(
            name='Work25',
        ),
        migrations.DeleteModel(
            name='Work26',
        ),
        migrations.DeleteModel(
            name='Work27',
        ),
        migrations.DeleteModel(
            name='Work28',
        ),
        migrations.DeleteModel(
            name='Work3',
        ),
        migrations.DeleteModel(
            name='Work4',
        ),
        migrations.DeleteModel(
            name='Work6',
        ),
        migrations.DeleteModel(
            name='Work7',
        ),
        migrations.DeleteModel(
            name='Work8',
        ),
        migrations.DeleteModel(
            name='Work9',
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={'verbose_name': '01. Mutaxassisliklar', 'verbose_name_plural': '01. Mutaxassisliklar'},
        ),
    ]
