# Generated by Django 2.2.3 on 2021-04-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_auto_20210428_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professiona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profarea', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': "02. Professional yo'nalish",
                'verbose_name_plural': "02. Professional yo'nalish",
            },
        ),
    ]
