# Generated by Django 2.2.3 on 2021-04-28 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_professiona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thchoprofar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profar', models.CharField(max_length=100, verbose_name='Nomi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Professiona')),
            ],
            options={
                'verbose_name': '03. Mutaxasisliklar',
                'verbose_name_plural': '03. Mutaxasisliklar',
            },
        ),
    ]
