# Generated by Django 2.2.3 on 2021-04-28 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_thchoprofar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialization',
            options={'verbose_name': '01. Mutaxassisliklar tajriba yuq', 'verbose_name_plural': '01. Mutaxassisliklar tajriba yuq'},
        ),
    ]
