# Generated by Django 2.2.3 on 2021-04-29 10:58

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0008_auto_20210428_1218'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacanciess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('job_title', models.CharField(max_length=100, verbose_name='Lavozim')),
                ('job_code', models.CharField(max_length=100, verbose_name='Ish kodi')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('moneys', models.CharField(choices=[('USD', 'USD'), ('RUB', 'RUB'), ('UZS', 'UZS')], max_length=100)),
                ('thesalaryfrom', models.CharField(max_length=100, verbose_name='$$$')),
                ('thesalaryto', models.CharField(max_length=100, verbose_name='$$$')),
                ('choosemo', models.CharField(choices=[('soliqlardan oldin', 'soliqlardan oldin'), ("qo'llarda", "qo'llarda")], max_length=100)),
                ('last_name', models.CharField(max_length=100, verbose_name='Familya')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('phone_name', models.CharField(max_length=100, verbose_name='Telefon nomer')),
                ('geolocation', models.CharField(max_length=100, verbose_name='Geo joylashuv')),
                ('emptype', models.CharField(choices=[("To'liq bandlik", "To'liq bandlik"), ("Yarim kunlik ish bilan ta'minlash", "Yarim kunlik ish bilan ta'minlash"), ('Loyiha ishi yoki bir martalik topshiriq', 'Loyiha ishi yoki bir martalik topshiriq'), ("Ko'ngillilik", "Ko'ngillilik"), ('Amaliyot', 'Amaliyot')], max_length=100)),
                ('worhou', models.CharField(choices=[("To'liq kun", "To'liq kun"), ('Smenali ish', 'Smenali ish'), ('Moslashuvchan jadval', 'Moslashuvchan jadval'), ('Uzoq ish', 'Uzoq ish')], max_length=100)),
                ('name', models.CharField(max_length=100, verbose_name='Familya Ism')),
                ('phone', models.CharField(max_length=100, verbose_name='Telefon nomer')),
                ('comment', models.CharField(max_length=100, verbose_name="Siz bilan bog'lanishning qulay vaqti")),
                ('profess', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.Professiona')),
                ('provinces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.Uzbekiston_provinces')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.Uzbekiston_region')),
                ('thchopr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.Thchoprofar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ish Berish eloni',
                'verbose_name_plural': 'Ish Berish eloni',
            },
        ),
    ]
