# Generated by Django 2.2.3 on 2021-04-29 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vacanciess',
        ),
    ]
